base: /transax/

title: Transax
description: Framework-agnostic JavaScript library for content internationalization.

plugins:
  - vuepress-plugin-tabs

head:
  - [ link, { rel: icon, href: /assets/favicon.ico } ]
  - [ link, { rel: apple-touch-icon, sizes: 180x180, href: /assets/apple-touch-icon.png } ]
  - [ link, { rel: icon, type: image/png, sizes: 32x32, href: /assets/favicon-32x32.png } ]
  - [ link, { rel: icon, type: image/png, sizes: 16x16, href: /assets/favicon-16x16.png } ]
  - [ link, { rel: manifest, href: /assets/site.webmanifest } ]

themeConfig:
  nav:
    - link: /introduction
      text: Guide
    - link: https://www.npmjs.com/package/transax
      text: NPM
    - link: https://github.com/tonybogdanov/transax
      text: GitHub
  sidebar:
    - title: Introduction
      path: /introduction
    - title: Installation
      path: /installation
    - title: Usage
      path: /usage/importing
      children:
        - /usage/importing
        - /usage/analysis
        - /usage/compilation
        - /usage/translation
        - /usage/interpolation
        - /usage/syntax
    - title: Advanced
      path: /advanced
    - title: API Reference
      path: /api
      children:
        - /api/interfaces/LoggerInterface
        - /api/interfaces/AnalyzerInterface
        - /api/interfaces/CompilerInterface
        - /api/interfaces/GeneratorInterface
        - /api/interfaces/TranslatorInterface
        - /api/classes/Logger
        - /api/classes/Analyzer
        - /api/classes/AnalyzerToken
        - /api/classes/Compiler
        - /api/classes/CompilerContext
        - /api/classes/CompilerToken
        - /api/classes/TextToken
        - /api/classes/LiteralToken
        - /api/classes/TernaryExpressionToken
        - /api/classes/ComparisonExpressionToken
        - /api/classes/CallExpressionToken
        - /api/classes/Generator
        - /api/classes/Translator
