base: /transax/

title: Transax
description: Framework-agnostic JavaScript library for content internationalization.

plugins:
  - vuepress-plugin-tabs

themeConfig:
  nav:
    - link: /introduction
      text: Guide
    - link: https://www.npmjs.com/package/transax
      text: NPM
    - link: https://github.com/tonybogdanov/transax
      text: GitHub
  sidebar:
    - title: Introduction
      path: /introduction
      collapsable: false
    - title: Installation
      path: /installation
      collapsable: false
    - title: Usage
      path: /usage/importing
      collapsable: false
      children:
        - /usage/importing
        - /usage/analysis
