name: build

on:
  push:
    branches: [ master ]
    tags: [ '*' ]

jobs:
  test:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Setup
        run: npm i

      - name: Run tests
        run: npm run test
