name: build

on:
  push:
    branches: [ master ]

jobs:
  purge_workflow_runs:
    name: Purge workflow runs
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        run: sudo apt-get install -y jq

      - name: Purge
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api repos/tonybogdanov/transax/actions/runs --paginate | \
          jq '.workflow_runs[] | .id' | \
          xargs -t -I{} sh -c "gh api -X DELETE /repos/tonybogdanov/transax/actions/runs/{} || true"

  test:
    name: Run tests
    if: github.event_name == 'push' && github.ref == 'refs/heads/master' && !contains(github.event.head_commit.message, 'release:')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup project
        run: npm i

      - name: Run tests
        run: npm run test

  test-with-coverage:
    name: Run tests with coverage
    if: github.event_name == 'push' && github.ref == 'refs/heads/master' && contains(github.event.head_commit.message, 'release:')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup project
        run: npm i

      - name: Run tests
        run: npm run test:coverage

      - name: Export coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage

  docs:
    name: Generate docs
    runs-on: ubuntu-latest
    needs: test-with-coverage

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup project
        run: npm i

      - name: Import coverage
        uses: actions/download-artifact@v3
        with:
          name: coverage
          path: coverage

      - name: Build docs
        run: npm run build:docs

      - name: Publish docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vuepress/dist

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: docs

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - name: Release
        run: npm publish || true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
